export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PARTICIPATED_PAPERS = "SET_PARTICIPATED_PAPERS";
export const SET_CREATED_PAPERS = "SET_CREATED_PAPERS";
export const START_ONBOARDING = "START_ONBOARDING";
export const END_ONBOARDING = "END_ONBOARDING";